version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=3000
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INSTANCE_ID=app_instance_1
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'

volumes:
  pgdata: 